//! Command line definitions using clap derive.
//!
//! Help is not generated by clap. It is printed from src/bin/jaka_cli_help.txt (see main.rs).

use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

/// The IO bank to address, the end tool or the control cabinet
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum IoWhere {
    Tool,
    Cabinet,
}

/// A digital state word, accepts on/off
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum OnOff {
    On,
    Off,
}

/// JAKA robotic arm driver
#[derive(Parser, Debug)]
#[command(
    name = "jaka-cli",
    version,
    about,
    long_about = None,
    disable_help_flag = true,
    disable_version_flag = true,
    disable_help_subcommand = true,
)]
pub struct Cli {
    /// Controller IP address
    #[arg(long, default_value = "10.5.5.100")]
    pub ip: String,

    /// Print the plan without connecting
    #[arg(long)]
    pub dry_run: bool,

    /// Show help, the content comes from src/help.txt
    #[arg(long, short = 'h')]
    pub help: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Read robot state: estop, power, enable, joint angles
    #[command(disable_help_flag = true)]
    Status,

    /// Power on and enable the robot to hold position
    #[command(disable_help_flag = true)]
    PowerOn,

    /// Disable servos and power off
    #[command(disable_help_flag = true)]
    PowerOff,

    /// Clear the e-stop error state, release the physical button first
    #[command(disable_help_flag = true)]
    EstopClear,

    /// Print the joint angles in degrees as JSON to stdout
    #[command(disable_help_flag = true)]
    Inspect,

    /// Print the TCP position relative to the base as JSON to stdout
    #[command(disable_help_flag = true)]
    InspectPos,

    /// Print the DH parameters as JSON to stdout
    #[command(disable_help_flag = true)]
    Dh,

    /// Power on, enable, then rotate the specified joint
    /// Rotate the specified joint
    #[command(disable_help_flag = true)]
    Rot {
        /// Joint to rotate, from 1 to 6
        #[arg(long, default_value_t = 6, value_parser = clap::value_parser!(i32).range(1..=6))]
        joint: i32,

        /// Rotation angle in degrees, negative reverses direction
        #[arg(long, default_value_t = 360.0, allow_negative_numbers = true)]
        deg: f64,

        /// Joint speed in radians per second
        #[arg(long, default_value_t = 0.8)]
        speed: f64,
    },

    /// Restore the joint angles recorded by inspect from a JSON file.
    /// Without a file the built-in default pose is used
    #[command(disable_help_flag = true)]
    Restore {
        /// Path to the JSON file produced by inspect, defaults to the built-in pose
        #[arg(value_name = "JSON_FILE")]
        file: Option<PathBuf>,

        /// Joint speed in radians per second
        #[arg(long, default_value_t = 100.0)]
        speed: f64,
    },

    /// Move the TCP to an absolute base-frame position, or with --rel to a
    /// position relative to the base pose. Repeating the same command is a
    /// no-op once the robot is already there
    #[command(disable_help_flag = true)]
    MoveTo {
        /// X coordinate in mm in the base frame
        #[arg(value_name = "X", allow_negative_numbers = true)]
        x: Option<f64>,

        /// Y coordinate in mm in the base frame
        #[arg(value_name = "Y", allow_negative_numbers = true)]
        y: Option<f64>,

        /// Z coordinate in mm in the base frame
        #[arg(value_name = "Z", allow_negative_numbers = true)]
        z: Option<f64>,

        /// Linear speed in mm/s
        #[arg(long, default_value_t = 100.0)]
        speed: f64,

        /// Treat x y z as offsets from the base pose instead of absolute coordinates
        #[arg(long)]
        rel: bool,

        /// Read the absolute target pose from an inspect-pos JSON file, position and orientation together
        #[arg(long, value_name = "POSE_FILE", conflicts_with_all = ["x", "y", "z"])]
        pose: Option<PathBuf>,

        /// The absolute target pose as an inspect-pos JSON string, position and orientation together
        #[arg(long, value_name = "JSON", conflicts_with_all = ["x", "y", "z", "pose"])]
        json: Option<String>,

        /// Target roll in degrees in the base frame, keep current when omitted
        #[arg(long, allow_negative_numbers = true)]
        rx: Option<f64>,

        /// Target pitch in degrees in the base frame, keep current when omitted
        #[arg(long, allow_negative_numbers = true)]
        ry: Option<f64>,

        /// Target yaw in degrees in the base frame, keep current when omitted
        #[arg(long, allow_negative_numbers = true)]
        rz: Option<f64>,
    },

    /// Save the current TCP position as the base pose for move-to
    #[command(disable_help_flag = true)]
    SetBase,

    /// Serve a TCP control protocol for a gamepad. Incremental motion
    /// commands abort the previous motion and start a new one
    #[command(disable_help_flag = true)]
    Serve {
        /// TCP port to listen on
        #[arg(long, default_value_t = 5533)]
        port: u16,

        /// Run without a controller, print the commands and reply with a
        /// simulated state for testing the client side
        #[arg(long)]
        mock: bool,
    },

    /// Print every tool and cabinet digital input and output plus the tool
    /// IO supply voltage as JSON to stdout
    #[command(disable_help_flag = true)]
    IoState,

    /// Read one digital input of the tool or the cabinet
    #[command(disable_help_flag = true)]
    Di {
        /// The IO bank: tool or cabinet
        #[arg(value_enum, value_name = "TOOL|CABINET")]
        io_where: IoWhere,

        /// Input index, from 0
        #[arg(value_name = "INDEX")]
        index: i32,
    },

    /// Set one digital output of the tool or the cabinet and read it back
    #[command(disable_help_flag = true)]
    Do {
        /// The IO bank: tool or cabinet
        #[arg(value_enum, value_name = "TOOL|CABINET")]
        io_where: IoWhere,

        /// Output index, from 0
        #[arg(value_name = "INDEX")]
        index: i32,

        /// The new state: on or off
        #[arg(value_enum, value_name = "ON|OFF")]
        state: OnOff,
    },

    /// Show the tool IO supply voltage, or set it when a mode is given:
    /// 24 for 24 V, 12 for 12 V, off to disable the supply
    #[command(disable_help_flag = true)]
    TioVout {
        /// The supply mode: 24, 12 or off, query when omitted
        #[arg(value_name = "24|12|OFF", value_parser = ["24", "12", "off"])]
        mode: Option<String>,
    },
}
